ATTACK_PATTERNS = {
    "sql_injection": [
        # Basic SQL injection patterns
        r"'(\s|\+)*(OR|AND)(\s|\+)*[0-9]",
        r"(\s|\+)*(OR|AND)(\s|\+)*[0-9](\s|\+)*=(\s|\+)*[0-9]",
        r"SELECT(\s|\+)*FROM",
        r"UNION(\s|\+)*SELECT",
        r"INSERT(\s|\+)*INTO",
        r"DROP(\s|\+)*TABLE",
        r"DELETE(\s|\+)*FROM",
        r"UPDATE(\s|\+)*SET",
        r"EXEC(\s|\+)*sp_",
        r"DECLARE(\s|\+)*@",
        r"EXECUTE(\s|\+)*immediate",
        r"SELECT(\s|\+)*password",
        r"SELECT(\s|\+)*\*",
        r"admin'--",
        r"1';\s*DROP\s+TABLE\s+users;\s*--",
        r"(\s|\+)*OR(\s|\+)*1=1",
        r"(\s|\+)*OR(\s|\+)*'1'='1",
        r"(\s|\+)*OR(\s|\+)*'a'='a",
        r"'(\s|\+)*OR(\s|\+)*username(\s|\+)*LIKE(\s|\+)*'%admin%'",
        r"'(\s|\+)*WAITFOR(\s|\+)*DELAY(\s|\+)*'[0-9:]+'--",
        r"(\s|\+)*ORDER(\s|\+)*BY(\s|\+)*[0-9]+",
        r"(\s|\+)*GROUP(\s|\+)*BY(\s|\+)*[0-9]+",
        r"';\s*EXEC(\s|\+)*xp_cmdshell",
        r"LOAD_FILE\s*\(",
        r"INTO(\s|\+)*OUTFILE",
        r"SLEEP\s*\(\s*[0-9]+\s*\)"
    ],
    "xss": [
        # Basic XSS patterns
        r"<script[^>]*>",
        r"</script\s*>",
        r"javascript:",
        r"vbscript:",
        r"data:text/html",
        r"onabort=",
        r"onblur=",
        r"onchange=",
        r"onclick=",
        r"ondblclick=",
        r"onerror=",
        r"onfocus=",
        r"onkeydown=",
        r"onkeypress=",
        r"onkeyup=",
        r"onload=",
        r"onmousedown=",
        r"onmousemove=",
        r"onmouseout=",
        r"onmouseover=",
        r"onmouseup=",
        r"onreset=",
        r"onresize=",
        r"onscroll=",
        r"onselect=",
        r"onsubmit=",
        r"onunload=",
        r"eval\s*\(",
        r"setTimeout\s*\(",
        r"setInterval\s*\(",
        r"Function\s*\(",
        r"document\.cookie",
        r"document\.write",
        r"document\.location",
        r"document\.URL",
        r"document\.documentURI",
        r"document\.domain",
        r"document\.referrer",
        r"window\.location",
        r"<img[^>]*src=['\"]?x['\"]?[^>]*onerror=",
        r"<svg[^>]*onload=",
        r"<body[^>]*onload=",
        r"<iframe[^>]*src=['\"]?javascript:",
        r"\"><script>",
        r"<div[^>]*style=['\"]?background-image:\s*url\(javascript:",
        r"<link[^>]*href=['\"]?javascript:",
        r"<meta[^>]*http-equiv=['\"]?refresh['\"]?[^>]*url=",
        r"<object[^>]*data=",
        r"<embed[^>]*src=",
        r"<form[^>]*action=['\"]?javascript:",
        r"<base[^>]*href=",
        r"<input[^>]*type=['\"]?image['\"]?[^>]*src=",
        r"<image[^>]*src=",
        r"<isindex[^>]*action=",
        r"alert\s*\(",
        r"prompt\s*\(",
        r"confirm\s*\(",
        r"expression\s*\(",
        r"fromCharCode",
        r"\\x[0-9a-fA-F]{2}",
        r"\\u[0-9a-fA-F]{4}"
    ],
    "path_traversal": [
        # Basic path traversal patterns
        r"\.\./",
        r"\.\.\\",
        r"%2e%2e/",
        r"%2e%2e%2f",
        r"\.\.%2f",
        r"%252e%252e%252f",
        r"..%c0%af",
        r"%c0%ae%c0%ae/",
        r"file:",
        r"file%3a",
        r"../etc/passwd",
        r"..%2fetc%2fpasswd",
        r"/var/www/../../etc/passwd",
        r"../../../etc/passwd",
        r"../../../../etc/passwd",
        r"../../../../../etc/passwd",
        r"../../../../../../etc/passwd",
        r"../../../../../../../etc/passwd",
        r"../../../../../../../../etc/passwd",
        r"../../../../../../../../../etc/passwd",
        r"..\\Windows\\win.ini",
        r"..%5cwindows%5cwin.ini",
        r"..%255c..%255c..%255cwindows%255cwin.ini",
        r"/etc/shadow",
        r"C:\\boot.ini",
        r"WEB-INF/web.xml",
        r"WEB-INF/classes/",
        r"../../../wp-config.php",
        r"php://filter",
        r"php://input",
        r"php://expect",
        r"php://wrapper",
        r"phar://",
        r"data:text/plain",
        r"zip://",
        r"jar://",
        r"file:///etc/passwd",
        r"\\\\localhost\\c$\\",
        r"\\\\127.0.0.1\\c$\\",
        r"\\\\..\\",
        r"file://\/\/\/"
    ],
    "command_injection": [
        # Basic command injection patterns
        r"\|\s*[a-zA-Z]+",
        r"\&\s*[a-zA-Z]+",
        r";\s*[a-zA-Z]+",
        r"`[^`]+`",
        r"\$\([^)]+\)",
        r"\$\{[^}]+\}",
        r"\|\s*cat\s+",
        r"\|\s*ls",
        r"\|\s*id",
        r"\|\s*dir",
        r"\|\s*pwd",
        r"\|\s*whoami",
        r"\|\s*wget",
        r"\|\s*curl",
        r"\|\s*nc",
        r"\|\s*netcat",
        r"\|\s*nslookup",
        r"\|\s*ping",
        r"\|\s*telnet",
        r"\|\s*bash",
        r"\|\s*sh",
        r"\|\s*python",
        r"\|\s*perl",
        r"\|\s*ruby",
        r"\|\s*nmap",
        r"\$\(whoami\)",
        r";\s*ping\s+-c\s+[0-9]",
        r";\s*sleep\s+[0-9]",
        r"&&\s*ping\s+-c\s+[0-9]",
        r"&&\s*sleep\s+[0-9]",
        r"\|\s*nc\s+",
        r"&&\s*curl\s+",
        r";\s*bash\s+-i\s+>&\s*/dev/tcp/",
        r"2>&1",
        r">/dev/null",
        r"><script>",
        r"\|\s*base64",
        r"\|\s*xxd",
        r"\|\s*hexdump",
        r"%0A[a-zA-Z]+",  # URL encoded newline followed by command
        r"%0D[a-zA-Z]+",  # URL encoded carriage return followed by command
        r"\$\{\{[^}]+\}\}",  # Template injection
        r"\{\{[^}]+\}\}"   # Template injection
    ],
    "prototype_pollution": [
        # Basic prototype pollution patterns
        r"__proto__",
        r"constructor",
        r"prototype",
        r"__proto__\[.+?\]",
        r"constructor\.prototype",
        r"Object\.prototype",
        r"__defineGetter__",
        r"__defineSetter__",
        r"__lookupGetter__",
        r"__lookupSetter__",
        r"hasOwnProperty",
        r"isPrototypeOf",
        r"propertyIsEnumerable",
        r"toLocaleString",
        r"toString",
        r"valueOf",
        r"constructor\.constructor",
        r"__proto__\.constructor",
        r"prototype\.constructor",
        r"__proto__\.admin",
        r"constructor\.prototype\.admin",
        r"prototype\[.+?\]",
        r"constructor\.prototype\[.+?\]",
        r"Object\.setPrototypeOf",
        r"Reflect\.setPrototypeOf",
        r"Object\.assign",
        r"JSON\.parse",
        r"JSON\.stringify"
    ],
    "deserialization": [
        # Basic deserialization patterns
        r"rO0",  # Java serialized object marker
        r"O:[0-9]+:",  # PHP serialized object
        r"a:[0-9]+:",  # PHP serialized array
        r"s:[0-9]+:",  # PHP serialized string
        r"i:[0-9]+;",  # PHP serialized integer
        r"YTo",  # Base64 encoded PHP serialization
        r"Tzo",  # Base64 encoded PHP serialization
        r"YToxOntzOjg6ImNsYXNzbmFtZSI7czo2OiJTeXN0ZW0iO30=",
        r"Tzo5OiJQYWdlTW9kZWwiOjE6e",
        r"eyJyY2UiOiJfJF9GVU5DVC1fMyggJ3Rlc3QnICkiLCJwaHAiOiI8P3BocCBwaHBpbmZvKCk7Pz4ifQ==",
        r"YTowOnt9",  # Base64 encoded PHP array
        r"\x00\x00\x00[\x01-\x10]",  # Java serialization version
        r"javax\.xml\.transform\.Templates",
        r"com\.sun\.rowset\.JdbcRowSetImpl",
        r"org\.apache\.commons\.collections",
        r"java\.lang\.Runtime",
        r"java\.lang\.ProcessBuilder",
        r"java:comp/env/jdbc",
        r"java\.io\.ObjectInputStream",
        r"ObjectInputStream\.readObject",
        r"org\.python\.core\.PyFunction",
        r"org\.yaml\.snakeyaml",
        r"org\.springframework\.beans\.factory\.ObjectFactory",
        r"XmlDecoder",
        r"json\.loads",
        r"pickle\.loads",
        r"marshal\.loads",
        r"cPickle\.loads",
        r"ObjectInputStream",
        r"readObject",
        r"readUnshared"
    ],
    "jwt_manipulation": [
        # Basic JWT manipulation patterns
        r"eyJ[a-zA-Z0-9_-]+\.eyJ[a-zA-Z0-9_-]+\.",
        r"eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0",
        r"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJQUzM4NCIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJQUzUxMiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9",
        r"eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9",
        r"\"alg\":\s*\"none\"",
        r"\"typ\":\s*\"JWT\"",
        r"\"admin\":\s*true",
        r"\"admin\":\s*1",
        r"\"role\":\s*\"admin\"",
        r"\"isAdmin\":\s*true",
        r"\"iat\":",
        r"\"exp\":",
        r"\"nbf\":",
        r"\"sub\":",
        r"\"jti\":",
        r"\"kid\":",
        r"\"x5c\":",
        r"\"x5t\":",
        r"\"x5u\":",
        r"\"jwk\":",
        r"\"jku\":",
        r"\"kid\":\s*\"none\""
    ],
    "ssrf": [
        # Basic SSRF patterns
        r"localhost",
        r"127\.0\.0\.1",
        r"127\.0\.1\.1",
        r"127\.1\.1\.1",
        r"0\.0\.0\.0",
        r"::1",
        r"\[::1\]",
        r"0:0:0:0:0:0:0:1",
        r"0177\.0\.0\.1",  # Octal representation
        r"0x7f000001",     # Hex representation
        r"2130706433",     # Decimal representation
        r"017700000001",   # Mixed octal
        r"0x7f\.0\.0\.1",
        r"192\.168\.",
        r"10\.",
        r"172\.(1[6-9]|2[0-9]|3[0-1])\.",
        r"169\.254\.",
        r"169\.254\.169\.254",  # AWS metadata
        r"metadata\.google\.internal",  # GCP metadata
        r"169\.254\.170\.2",  # Azure metadata
        r"100\.100\.100\.200",  # Alibaba Cloud metadata
        r"fd00::",  # IPv6 unique local addresses
        r"fe80::",  # IPv6 link-local addresses
        r"file:///",
        r"ftp://",
        r"gopher://",
        r"http://localhost",
        r"https://localhost",
        r"http://[0:0:0:0:0:0:0:1]",
        r"https://[0:0:0:0:0:0:0:1]",
        r"dict://",
        r"ldap://",
        r"ldaps://",
        r"tftp://",
        r"ssh://",
        r"smtp://",
        r"telnet://",
        r"vnc://",
        r"mongodb://",
        r"redis://",
        r"jdbc:",
        r"jar:",
        r"netdoc:",
        r"ogg://",
        r"http://example.com@localhost",  # URL confusion
        r"http://localhost#example.com",  # URL fragment confusion
        r"http://127.0.0.1:25",  # SMTP port
        r"http://127.0.0.1:22",  # SSH port
        r"http://127.0.0.1:3306",  # MySQL port
        r"http://127.0.0.1:5432",  # PostgreSQL port
        r"http://127.0.0.1:6379",  # Redis port
        r"http://127.0.0.1:27017",  # MongoDB port
        r"http://127.0.0.1:11211",  # Memcached port
        r"http://127.0.0.1:9200"   # Elasticsearch port
    ],
    "nosql_injection": [
        # NoSQL injection patterns
        r"\$where\s*:",
        r"\$regex\s*:",
        r"\$gt\s*:",
        r"\$lt\s*:",
        r"\$gte\s*:",
        r"\$lte\s*:",
        r"\$ne\s*:",
        r"\$in\s*:",
        r"\$nin\s*:",
        r"\$exists\s*:",
        r"\$type\s*:",
        r"\$not\s*:",
        r"\$elemMatch\s*:",
        r"\$size\s*:",
        r"\$all\s*:",
        r"\$or\s*:",
        r"\$and\s*:",
        r"\$nor\s*:",
        r"\$expr\s*:",
        r"\$jsonSchema\s*:",
        r"\$text\s*:",
        r"\$mod\s*:",
        r"\$eq\s*:",
        r"\\u0024\\u0077\\u0068\\u0065\\u0072\\u0065",  # Unicode $where
        r"true,\s*\$where",
        r"false,\s*\$where",
        r",\s*\$where",
        r"{\s*password\s*:\s*1\s*}",
        r"{\s*password\s*:\s*{\s*\$ne\s*:\s*null\s*}\s*}",
        r"{\s*username\s*:\s*{\s*\$in\s*:\s*\[\s*\"admin\"\s*\]\s*}\s*}",
        r"ObjectId\(['\"][a-f0-9]{24}['\"]\)",
        r"ISODate\(['\"][^'\"]+['\"]\)",
        r"tojson\(",
        r"db\.collection\.findOne\(",
        r"db\.collection\.find\(",
        r"db\.collection\.update\(",
        r"db\.collection\.remove\("
    ],
    "xxe": [
        # XXE injection patterns
        r"<!DOCTYPE",
        r"<!ENTITY",
        r"SYSTEM\s+\"",
        r"PUBLIC\s+\"",
        r"<!ENTITY\s+%\s+[a-zA-Z0-9]+\s+SYSTEM",
        r"file:///etc/passwd",
        r"file:///c:/Windows/win.ini",
        r"<!ENTITY\s+[a-zA-Z0-9]+\s+SYSTEM",
        r"&[a-zA-Z0-9]+;",
        r"\]\]><",
        r"<!ATTLIST",
        r"<!NOTATION",
        r"<!ELEMENT",
        r"file://\/\/\/",
        r"php://filter/convert.base64-encode/resource=",
        r"expect://",
        r"data://text/plain;base64,",
        r"<svg xmlns=\"http://www.w3.org/2000/svg\"",
        r"<?xml version=\"1.0\"",
        r"xmlns:xi=\"http://www.w3.org/2001/XInclude\"",
        r"<xi:include href=\"",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"file:///etc/passwd\"\s*>",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"file:///etc/shadow\"\s*>",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"file:///c:/boot.ini\"\s*>",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"http://",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"https://",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"ftp://",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"php://",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"gopher://",
        r"<!ENTITY\s+xxe\s+SYSTEM\s+\"jar://"
    ],
    "csrf": [
        # CSRF patterns
        r"<form[^>]*action=",
        r"<form[^>]*method=['\"]?(post|POST)['\"]?",
        r"<form[^>]*onsubmit=",
        r"<img[^>]*src=['\"]?http",
        r"<iframe[^>]*src=['\"]?http",
        r"$.ajax\(",
        r"XMLHttpRequest\(",
        r"fetch\(",
        r"new Request\(",
        r"navigator.sendBeacon\(",
        r"<script[^>]*src=['\"]?http",
        r"document.createElement\(['\"]form['\"]\)",
        r"document.createElement\(['\"]img['\"]\)",
        r"document.createElement\(['\"]iframe['\"]\)",
        r"document.createElement\(['\"]script['\"]\)",
        r"document.body.appendChild\(",
        r"document.forms\[0\].submit\(\)",
        r"document.createElement\(['\"]button['\"]\)",
        r"document.createElement\(['\"]a['\"]\)"
    ],
    "file_upload": [
        # File upload bypass patterns
        r"\.php",
        r"\.jsp",
        r"\.asp",
        r"\.aspx",
        r"\.html",
        r"\.js",
        r"\.exe",
        r"\.phtml",
        r"\.pht",
        r"\.phar",
        r"\.shtml",
        r"\.php3",
        r"\.php4",
        r"\.php5",
        r"\.php7",
        r"\.phps",
        r"\.cgi",
        r"\.pl",
        r"\.py",
        r"\.rb",
        r"\.sh",
        r"\.bat",
        r"\.cmd",
        r"\.dll",
        r"\.htaccess",
        r"\.config",
        r"\.ini",
        r"\.pht%00.jpg",
        r"\.php%00.jpg",
        r"\.php.jpg",
        r"\.php;.jpg",
        r"Content-Type:\s*application/x-php",
        r"Content-Type:\s*application/octet-stream",
        r"Content-Type:\s*text/x-php",
        r"Content-Type:\s*application/x-httpd-php",
        r"GIF89a;",
        r"<\?php",
        r"<\?=",
        r"<script language=\"php\"",
        r"%PDF-1.3\s*%PHP",
        r"#!/usr/bin/perl",
        r"#!/bin/sh",
        r"#!/bin/bash",
        r"MZ\x90\x00",  # PE executable signature
        r"\x7FELF"      # ELF executable signature
    ],
    "http_response_splitting": [
        # HTTP response splitting patterns
        r"%0D%0A",
        r"\r\n",
        r"%0d%0a",
        r"%0D%0ASet-Cookie:",
        r"%0d%0aSet-Cookie:",
        r"\r\nSet-Cookie:",
        r"%0D%0AContent-Type:",
        r"%0d%0aContent-Type:",
        r"\r\nContent-Type:",
        r"%0D%0ALocation:",
        r"%0d%0aLocation:",
        r"\r\nLocation:",
        r"%0D%0AContent-Disposition:",
        r"%0d%0aContent-Disposition:",
        r"\r\nContent-Disposition:",
        r"%0D%0AHTTP/1.1",
        r"%0d%0aHTTP/1.1",
        r"\r\nHTTP/1.1"
    ],
    "ldap_injection": [
        # LDAP injection patterns
        r"\*\)",
        r"\(\|\(",
        r"\)\|\(",
        r"\(\&\(",
        r"\)\&\(",
        r"\)\)",
        r"\(\(",
        r"\*",
        r"\\\*\\\)",
        r"cn=",
        r"sn=",
        r"uid=",
        r"ou=",
        r"dc=",
        r"objectClass=",
        r"administratoraccounts",
        r"[^a-zA-Z0-9]admin[^a-zA-Z0-9]",
        r"[^a-zA-Z0-9]root[^a-zA-Z0-9]",
        r"[^a-zA-Z0-9]manager[^a-zA-Z0-9]"
    ],
    "ssrf_dns_rebinding": [
        # SSRF DNS rebinding patterns
        r"http://[^.]*[.][^.]*[.][a-zA-Z0-9-]+[.]127[.]0[.]0[.]1[.]nip[.]io",
        r"http://www[.]example[.]com##@127[.]0[.]0[.]1",
        r"http://localtest[.]me",
        r"http://customer1[.]app[.]127[.]0[.]0[.]1[.]nip[.]io",
        r"http://bugbounty[.]dnsai[.]com",
        r"http://1u.ms",
        r"http://4u.ms",
        r"http://10u.ms",
        r"evil[.]com[.]127[.]0[.]0[.]1[.]xip[.]io",
        r"evil[.]com[.][.]127[.]0[.]0[.]1[.]xip[.]io",
        r"evil[.]com[.]attacker-controlled-dns[.]com"
    ]
}